### ISSUE TITLE
Can I run Atomes by a pure command-line interaction method in HPC clusters

### ISSUE THREAD

**Issue by sailangyf** [Slookeur/Atomes#18]
Hi Dr. Sébastien Le Roux,

Thank you for your efforts to develop this excellent software. 
I am writing to ask if and how I can run atomes to analyze the rings data and output the results by a pure command-line method? Because I want to use it to do the ring's analysis but which is only part of the post-process of the simulation, and if I can run it just by command-line interaction, it will be convenient to run by a shell scipt on HPC clusters.

Best,
Fan

**Comment by Slookeur** [comment]
Hello, 
and thank you, no you cannot, however for that purpose you can look into RINGS, 
another of my codes, unfortunately the official web site went down last year because of an update
of sourceforge my-sql database. 
You can  still look into it using web.archive.org: 

https://web.archive.org/web/20220501000000*/rings-code.sourceforge.net

So that you can access the documentation, latest releases are available here: 

https://sourceforge.net/projects/rings-code/

RINGS was design for HPC puroposes (MPI //) so it will do what you are interested in, 
however I did not dig into this code for some time and it is not as optimized as atomes can be, 
hopefully one day I will have the time to implement in RINGS what I did in atomes to improve it. 

Hope this help

**Comment by sailangyf** [comment]
Thank you very much!
Got it! Actually I know RINGS but I found I can't open the website. So your response really helps a lot. Now I can look at the manual using web.archive.org.
Thank you again. 
Best wishes,
Fan
