### ISSUE TITLE
Laptop restarted when open an XYZ file and set the box parameters & Feature Request

### ISSUE THREAD

**Issue by sailangyf** [Slookeur/Atomes#19]
Hello Dr. Sébastien Le Roux,

I met with a problem when I opened an xyz file and set the box size and boundary condition. I don't know why my laptop directly crushed and was restarted automatically. I don't know if it's my laptop's problem or Atomes' problem, actually I never met with this problem. I tried 3 times, but failed every time.
Here is some information in case you need to test it:
Atomes version: 1.1.14
Windows System Version: Windows 11 23H2 22631.3447
My laptop is Lenovo XiaoXinPro 14 APH8, the cpu is  AMD Ryzen 7 7840HS with Radeon 780M Graphics.
The attachment is the XYZ file for your test.

[dump_IPG40_40000_sample.zip](https://github.com/Slookeur/Atomes/files/15022313/dump_IPG40_40000_sample.zip)

By the way, I wonder if you have the plan to add the feature of supporting lammps dump format file input? The request originated from two reasons:
1) LAMMPS is quite popular recently.
2) Yes I can dump xyz format file use dump_modify in LAMMPS, but I found that there are some restrictions for XYZ file. For instance, in my system, I have type1: Fe3+, type2: Fe2+, type3: P, type4: O, this can be specifically defined in LAMMPS and output in LAMMPS dump file. However, for XYZ file, the valence of element can not be defined, which means Fe3+ and Fe2+ are exactly the same. There is no doubt we will lose some information. That's why it came across in my mind if you will add features in Atomes to support read LAMMPS dump file.

Thanks a lot.

Best regards,
Fan

**Comment by Slookeur** [comment]
Hello, 
first of all I have no issues opening your file, and the size of the file is unlikely to be a problem. 
So some information is missing to understand what is going on: what are you doing exactly and 
what box size are you using ? 
Also the coordinates in your file are Cartesian, just to avoid any issue with that. 

I am currently working on the LAMMPS side of things, so to write, because you are absolutely correct: 
LAMMPS is quite popular these days ... not sure when or if I will have the opportunity to look into what you are mentioning ... 
However and that is the good news for you atomes is an open source software, and your absolutely 
welcome to participate and work on this features (or anybody else interested in), note that I will do 
my best to help you out if you decide to step in ;-)

Best regards.

S.

**Comment by sailangyf** [comment]
Hello Dr. Sébastien Le Roux,
Thanks  a lot, I realized the problem is when I edited the box and periodicity, I entered edge values into angle part and angle values into edge part. That's a really stupid mistake. Maybe I should not work today. :-(   Sorry for that!
Meanwhile, regarding the part of adding feature of reading LAMMPS Dump File or give more support to LAMMPS pre/post-processing, I think it's really meaningful and sometimes necessary. I am interested in contributing to it if possible after I finish my current project and have more spare time. But first I need to improve my programming capability then. :-|
Thank you again for you efforts to develop an excellent software, especially important for analysing amorphous material.
Best regards,
Fan
